# $wallpaper_path = ~/Pictures/Wallpapers/default.jpg
# preload = $wallpaper_path
# wallpaper = eDP-1,$wallpaper_path
splash = false

wallpaper{
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/default.jpg
    fit_mode = cover
}