#!/bin/bash

echo "###########################################"
echo "Arch Linux install"
echo "###########################################"
pacman -S --needed --noconfirm archlinux-keyring
echo "Set the console keyboard layout"
ls /usr/share/kbd/keymaps/**/*.map.gz |  grep us
loadkeys us

echo "Update the system clock"
timedatectl set-ntp true

clear
lsblk
fdisk -l
echo "Format the partitions"
echo "Enter EFI partition"
read efi_partition
echo "Enter swap partition"
read swap_partition
echo "Enter root partition"
read root_partition

echo "***************************************"
echo "efi_partition : /dev/$efi_partition"
echo "swap_partition : /dev/$swap_partition"
echo "root_partition : /dev/$root_partition"
echo "***************************************"
echo "Continue:any --- Esc: Ctrl+c "
read holded

mkswap /dev/$swap_partition
mkfs.ext4 /dev/$root_partition

echo "Mount the file systems"
swapon /dev/$swap_partition
mount /dev/$root_partition /mnt

if [ -n "$efi_partition" ]
then
    mkfs.fat -F 32 "/dev/$efi_partition"
    mount --mkdir /dev/$efi_partition /mnt/boot/efi
else
    echo "Warning: \$efi_partition variable is null or an empty string."
fi

echo "Install essential packages"
pacstrap -K /mnt base linux linux-firmware vim git 

echo "Generate an fstab file"
genfstab -U /mnt >> /mnt/etc/fstab

echo "Copying dotfiles"
cp -r dotfiles /mnt

echo "Chroot"
echo "run: bash dotfiles/shell/scripts/settings"
arch-chroot /mnt
umount -R /mnt
