#!/bin/bash
## enter su mode
## chmod 744 -R ~/scripts
# #   rwx
# 0   000
# 1   001
# 2   010
# 3   011
# 4   100
# 5   101
# 6   110
# 7   111
echo "###########################################" 
echo "start" 
date +'%d/%m/%Y %I:%M:%S'
echo "###########################################" 

echo "###########################################" 
echo "coping config files" 
echo "###########################################" 

mkdir  ~/.local/share/Trash
mkdir ~/backups/
cp -v ~/* ~/backups/
cp -v ~/.* ~/backups/
# generate default config files for ranger with
#ranger --copy-config=all

sed -i '/daniel torres/,$d' ~/.bashrc
cat ~/.bashrc_tail >> ~/.bashrc
cat ~/.history >> ~/.bash_history

chmod 774 ~/.config/bspwm/bspwmrc
chmod 774 ~/.config/sxhkd/sxhkdrc
chmod 774 ~/.config/polybar/launch.sh

git clone https://gitlab.com/danieltorresgitlab/emacs.git ~/.emacs.d

# # disable time automatic synchronization
# timedatectl set-ntp 0
# timedatectl set-timezone UTC
# timedatectl set-local-rtc 0
# # set timezone
# cp /usr/share/zoneinfo/America/Caracas /etc/localtime

# timedatectl set-timezone "America/Caracas"
# # set date and time with: 
# # timedatectl set-time '2015-11-20 16:14:50'
# timedatectl status
# # set hardware clock from system clock
# hwclock --systohc
# # read hardware clock
# hwclock --show

echo "###########################################" 
echo "end" 
date +'%d/%m/%Y %I:%M:%S'
echo "###########################################" 
