#!/bin/bash

## chmod 744 -R ~/scripts
# #   rwx
# 0   000
# 1   001
# 2   010
# 3   011
# 4   100
# 5   101
# 6   110
# 7   111
echo "###########################################"
echo "start"
date +'%d/%m/%Y %I:%M:%S'
echo "###########################################"

echo "###########################################"
echo "coping config files"
echo "###########################################"

mkdir  ~/.local/share/Trash
mkdir ~/backups/
cp -v ~/* ~/backups/
cp -v ~/.* ~/backups/

sed -i '/daniel torres/,$d' ~/.bashrc
cat ~/.bashrc_tail >> ~/.bashrc
cat ~/.history >> ~/.bash_history

chmod 774 ~/.config/bspwm/bspwmrc
chmod 774 ~/.config/sxhkd/sxhkdrc
chmod 774 ~/.config/polybar/launch.sh

#bash ~/scripts/touchpad

echo "###########################################"
echo "end"
date +'%d/%m/%Y %I:%M:%S'
echo "###########################################"
