#!/bin/bash

echo "###########################################"
echo "start"
date +'%d/%m/%Y %I:%M:%S'
echo "#######################################################"

echo "###########################################"
echo "coping and cloning config files"
echo "###########################################"

# cp /home/daniel/dotfiles/config/70-synaptics.conf /etc/X11/xorg.conf.d/70-synaptics.conf
# cp /home/daniel/dotfiles/config/20-amd-gpu.conf /etc/X11/xorg.conf.d/20-amd-gpu.conf
cp /home/daniel/dotfiles/config/power.rules  /etc/udev/rules.d/power.rules

su daniel -c "mkdir /home/daniel/backups/"
su daniel -c "cp -v ~/* /home/daniel/backups/"
su daniel -c "cp -v ~/.* /home/daniel/backups/"
su daniel -c "rm /home/daniel/.bash_profile"

su daniel -c "stow -d /home/daniel/dotfiles -t /home/daniel shell config"
su daniel -c "chmod 744 -R /home/daniel/scripts"
su daniel -c "sed -i '/daniel torres/,\$d' /home/daniel/.bashrc"
su daniel -c "cat /home/daniel/.bashrc_tail >> /home/daniel/.bashrc"

su daniel -c "chmod 774 /home/daniel/.config/bspwm/bspwmrc"
su daniel -c "chmod 774 /home/daniel/.config/sxhkd/sxhkdrc"
su daniel -c "chmod 774 /home/daniel/.config/polybar/launch.sh"

rm -rf /dotfiles

echo "###########################################"
echo "end"
date +'%d/%m/%Y %I:%M:%S'
echo "###########################################"
exit