#!/bin/bash

echo "Enter username"
read user
home="/home/$user"

echo "###########################################"
echo "start"
date +'%d/%m/%Y %I:%M:%S'
echo "#######################################################"

echo "###########################################"
echo "coping and cloning config files"
echo "###########################################"

if [[ "$user" != "vm" ]]; then
    cp $home/config/70-synaptics.conf /etc/X11/xorg.conf.d/70-synaptics.conf
    cp $home/dotfiles/config/20-amd-gpu.conf /etc/X11/xorg.conf.d/20-amd-gpu.conf
    cp $home/dotfiles/config/power.rules  /etc/udev/rules.d/power.rules
fi

su $user -c "mkdir $home/backups/"
su $user -c "cp -v ~/* $home/backups/"
su $user -c "cp -v ~/.* $home/backups/"
su $user -c "rm $home/.bash_profile"

su $user -c "stow -d $home/dotfiles -t $home shell config"
su $user -c "chmod 744 -R $home/scripts"
su $user -c "sed -i '/daniel torres/,\$d' $home/.bashrc"
su $user -c "cat $home/.bashrc_tail >> $home/.bashrc"

su $user -c "chmod 774 $home/.config/bspwm/bspwmrc"
su $user -c "chmod 774 $home/.config/sxhkd/sxhkdrc"
su $user -c "chmod 774 $home/.config/polybar/launch.sh"

rm -rf /dotfiles

echo "###########################################"
echo "end"
date +'%d/%m/%Y %I:%M:%S'
echo "###########################################"
exit
