#!/bin/bash

echo "Enter username"
read username
HOME = "/home/$username"

echo "###########################################"
echo "start"
date +'%d/%m/%Y %I:%M:%S'
echo "#######################################################"

echo "###########################################"
echo "coping and cloning config files"
echo "###########################################"

if [[ "$username" != "vm" ]]; then
    cp $HOME/config/70-synaptics.conf /etc/X11/xorg.conf.d/70-synaptics.conf
    cp $HOME/dotfiles/config/20-amd-gpu.conf /etc/X11/xorg.conf.d/20-amd-gpu.conf
    cp $HOME/dotfiles/config/power.rules  /etc/udev/rules.d/power.rules
fi

su $username -c "mkdir $HOME/backups/"
su $username -c "cp -v ~/* $HOME/backups/"
su $username -c "cp -v ~/.* $HOME/backups/"
su $username -c "rm $HOME/.bash_profile"

su $username -c "stow -d $HOME/dotfiles -t $HOME shell config"
su $username -c "chmod 744 -R $HOME/scripts"
su $username -c "sed -i '/daniel torres/,\$d' $HOME/.bashrc"
su $username -c "cat $HOME/.bashrc_tail >> $HOME/.bashrc"

su $username -c "chmod 774 $HOME/.config/bspwm/bspwmrc"
su $username -c "chmod 774 $HOME/.config/sxhkd/sxhkdrc"
su $username -c "chmod 774 $HOME/.config/polybar/launch.sh"

rm -rf /dotfiles

echo "###########################################"
echo "end"
date +'%d/%m/%Y %I:%M:%S'
echo "###########################################"
exit
