#!/bin/bash

echo "###########################################"
echo "System essential config"
echo "###########################################"
echo "Time zone"
timedatectl set-ntp true
# ln -sf /usr/share/zoneinfo/America/Caracas /etc/localtime
ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
# echo "set hardware clock from system clock"
hwclock --systohc
hwclock --show

# echo "disable time automatic synchronization"
# timedatectl set-ntp 0
# timedatectl set-timezone UTC
# timedatectl set-local-rtc 0

# timedatectl set-timezone "America/Caracas"
# echo "set date and time with:"
# timedatectl set-time '2015-11-20 16:14:50'
timedatectl status

echo "Create a new file /etc/vconsole.conf to make the changes persistent keyboard layout"
echo "KEYMAP=us" >> /etc/vconsole.conf
echo "LANG=en_US.UTF-8" >> /etc/locale.conf

echo "Localization : edit /etc/locale.gen uncomment en_US.UTF-8 UTF-8"
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen

echo "Network configuration: Create the hostname file"
echo "archlinux" >> /etc/hostname

echo "Add to /etc/hosts"
echo "127.0.0.1        localhost" >> /etc/hosts
echo "::1              localhost" >> /etc/hosts
echo "127.0.1.1        archlinux.localdomain archlinux" >> /etc/hosts

pacman -S --noconfirm networkmanager dhcpcd netctl wpa_supplicant dialog
systemctl enable NetworkManager
systemctl start NetworkManager.service

echo "Root password"
passwd

echo "Add new user daniel and install sudo"
useradd -m daniel
passwd daniel
usermod -aG wheel,audio,video,optical,storage daniel
pacman -S --noconfirm sudo 
echo "Uncomment the %wheel ALL=(ALL) ALL to allows people in group wheel to run all commands"
visudo

echo "Boot loader"
pacman -S --noconfirm grub efibootmgr dosfstools os-prober mtools

clear
echo "Verify the boot mode"
ls /sys/firmware/efi/efivars
echo "Enter bootloader:"
echo "BIOS  = 0"
echo "UEFI = 1"
read bootloader
clear
lsblk
fdisk -l
echo "Enter bootloader partition"
read boot
if [ ${bootloader:=0} -gt 0 ]
then
    echo "Mount FAT32 EFI partition"
    mount --mkdir /dev/$boot /boot/efi
    grub-install --efi-directory=/boot/efi --target=x86_64-efi  --bootloader-id=grub_uefi --recheck
else
    echo "grub-install /dev/$boot"
    grub-install /dev/$boot
fi

grub-mkconfig -o /boot/grub/grub.cfg
#echo "Install packages"
#bash /dotfiles/shell/scripts/packages
exit
