#!/bin/bash

echo "#######################################################"
echo "updating repositories and installing packages"
echo "#######################################################"
pacman -Syu
pacman -S --needed --noconfirm base-devel curl htop wget xorg stow screen
pacman -S --needed --noconfirm xdo clang cmake
pacman -S --needed --noconfirm emacs vim vifm
pacman -S --needed --noconfirm compton feh arandr playerctl pavucontrol
pacman -S --needed --noconfirm dmenu zathura mpv imagemagick flameshot
pacman -S --needed --noconfirm python-pip python-virtualenv 
pacman -S --needed --noconfirm udisks2 acpi
pacman -S --needed --noconfirm mutt rtorrent transmission-cli
pacman -S --needed --noconfirm ufw gufw firejail apparmor lxc
echo "###########################################"
echo "installing xfce"
echo "###########################################"
pacman -S --needed --noconfirm  xfce4 xfce4-goodies 
pacman -S --needed --noconfirm  lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings 
pacman -S --needed --noconfirm  capitaine-cursors arc-gtk-theme xdg-user-dirs-gtk file-roller network-manager-applet
systemctl enable lightdm -f
cp /etc/lightdm/lightdm.conf /etc/lightdm/lightdm.conf.orig
sed -i 's/#greeter-session=.*/greeter-session=lightdm-gtk-greeter/' /etc/lightdm/lightdm.conf

echo "###########################################"
echo "installing firefox"
echo "###########################################"
sudo pacman -S --needed --noconfirm  firefox

# echo "###########################################"
# echo "installing containers and virtual machine tools"
# echo "###########################################"

# pacman -S --needed --noconfirm docker docker-compose
# pacman -S --needed --noconfirm qemu-full virt-manager libvirt edk2-ovmf dnsmasq 
# systemctl enable libvirtd.service
# systemctl start libvirtd.service
# systemctl status libvirtd.service

# echo "###########################################"
# echo "creating virtualenv for python"
# echo "###########################################"

# pip install --upgrade pip
# virtualenv -p python3 ~/.venv/youtube-dl
# pip install --upgrade pip
# pip install youtube-dl

echo "###########################################"
echo "cloning and building packages"
echo "###########################################"

folder="/home/daniel"
su daniel -c "git clone https://github.com/danieltorrescode/dotfiles.git $folder/dotfiles"
cd $folder/dotfiles
su daniel -c  "stow shell config"
su daniel -c "chmod 744 -R $folder/scripts"
su daniel -c "bash $folder/scripts/config"

su daniel -c "git clone https://github.com/danieltorrescode/st.git $folder/st"
rm $folder/st/config.h
make -C $folder/st/
make -C $folder/st/ clean install

# to add color to st use http://terminal.sexy/
# generate palette with pywall or colorz
# and edit st/config.def.h and rebuild
# patching ex:
# patch < $patch
# su daniel -c "patch -d st/ < patches/$patch"

echo "###########################################"
echo "installing window manager"
echo "###########################################"
echo "***** bspwm *****"
pacman -S --needed --noconfirm bspwm sxhkd polybar

echo "***** i3 *****"
pacman -S --needed --noconfirm i3

echo "***** dwm *****"
su daniel -c "git clone https://github.com/danieltorrescode/dwm.git $folder/dwm"
rm $folder/dwm/config.h
make -C $folder/dwm/
make -C $folder/dwm/ clean install

echo "***** emacs *****"
su daniel -c "git clone https://github.com/danieltorrescode/emacs.git $folder/.emacs.d"

echo "***** vim *****"
su daniel -c "git clone https://github.com/VundleVim/Vundle.vim.git $folder/.vim/bundle/Vundle.vim"

echo "***** yay *****"
pacman -S --needed --noconfirm go
su daniel -c "git clone https://aur.archlinux.org/yay.git $folder/yay"
chown -R  daniel:daniel $folder/yay
cd $folder/yay
echo "run: makepkg -si"
echo "then run: yay --version"
su daniel
rm -rf /dotfiles
exit