#!/bin/bash

## chmod 744 -R /home/daniel/scripts
# #   rwx
# 0   000
# 1   001
# 2   010
# 3   011
# 4   100
# 5   101
# 6   110
# 7   111
echo "###########################################"
echo "start"
date +'%d/%m/%Y %I:%M:%S'
echo "#######################################################"
echo "updating repositories and installing packages"
echo "#######################################################"
pacman -S --needed --noconfirm archlinux-keyring
pacman -Syu
pacman -S --needed --noconfirm base-devel curl htop wget stow screen wpa_supplicant dhclient
pacman -S --needed --noconfirm xorg xorg-xinit xf86-input-synaptics xf86-input-libinput xdo clang cmake
pacman -S --needed --noconfirm gnu-free-fonts ttf-hack ttf-liberation ttf-ubuntu-font-family
pacman -S --needed --noconfirm emacs vim vifm neofetch tmux bash-completion
pacman -S --needed --noconfirm picom feh arandr playerctl pavucontrol pulseaudio
pacman -S --needed --noconfirm bluez bluez-utils blueman pulseaudio-bluetooth
pacman -S --needed --noconfirm dmenu slock zathura zathura-pdf-mupdf mpv imagemagick 
pacman -S --needed --noconfirm flameshot liferea lxappearance-gtk3
pacman -S --needed --noconfirm python-pip python-virtualenv 
pacman -S --needed --noconfirm udisks2 udiskie acpi numlockx 
pacman -S --needed --noconfirm mutt rtorrent transmission-cli
pacman -S --needed --noconfirm ufw gufw firejail apparmor lxc keepassxc
pacman -S --needed --noconfirm pamixer brightnessctl xbacklight mpd mpc
pacman -S --needed --noconfirm xdotool lsd bat dunst cronie
pacman -S --needed --noconfirm rofi kitty alacritty starship fzf ncdu 
pacman -S --needed --noconfirm zsh zsh-autosuggestions zsh-completions zsh-syntax-highlighting zsh-theme-powerlevel10k

echo "###########################################"
echo "AMD drivers"
echo "###########################################"
lspci -k | grep VGA
pacman -S --noconfirm xf86-video-amdgpu xf86-video-ati vulkan-radeon 
pacman -S --noconfirm libva-mesa-driver mesa-vdpau mesa mesa-demos
# sudo pacman -S --noconfirm --needed lib32-mesa vulkan-radeon lib32-vulkan-radeon 
# sudo pacman -S --noconfirm --needed vulkan-icd-loader lib32-vulkan-icd-loader

echo "###########################################"
echo "installing xfce"
echo "###########################################"
pacman -S --needed --noconfirm  xfce4 xfce4-goodies 
pacman -S --needed --noconfirm  capitaine-cursors arc-gtk-theme xdg-user-dirs-gtk file-roller network-manager-applet
pacman -S --needed --noconfirm  lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings 
systemctl enable lightdm -f
cp /etc/lightdm/lightdm.conf /etc/lightdm/lightdm.conf.orig
sed -i 's/#greeter-session=.*/greeter-session=lightdm-gtk-greeter/' /etc/lightdm/lightdm.conf

echo "###########################################"
echo "installing firefox"
echo "###########################################"
pacman -S --needed --noconfirm  firefox

echo "###########################################"
echo "installing containers and virtual machine tools"
echo "###########################################"

pacman -S --needed --noconfirm docker docker-compose
pacman -S --needed --noconfirm qemu-full virt-manager dnsmasq 

echo "###########################################"
echo "working with systemctl"
echo "###########################################"
systemctl enable ufw
systemctl enable cronie.service
systemctl start cronie.service
systemctl disable libvirtd.service
systemctl disable docker.service
systemctl disable bluetooth.service

newgrp libvirt
usermod -a -G libvirt daniel

echo "###########################################"
echo "creating virtualenv for python"
echo "###########################################"

pip install --upgrade pip
virtualenv -p python3 /home/daniel/.venv/python

echo "###########################################"
echo "cloning and building packages"
echo "###########################################"

su daniel -c "git clone https://github.com/danieltorrescode/dotfiles.git /home/daniel/dotfiles"
cd /home/daniel/dotfiles
rm /home/daniel/.bash_profile
cp /home/daniel/dotfiles/config/70-synaptics.conf /etc/X11/xorg.conf.d/70-synaptics.conf
cp /home/daniel/dotfiles/config/20-amd-gpu.conf /etc/X11/xorg.conf.d/20-amd-gpu.conf
cp /home/daniel/dotfiles/config/power.rules  /etc/udev/rules.d/power.rules

su daniel -c "git clone https://github.com/danieltorrescode/st.git /home/daniel/st"
rm /home/daniel/st/config.h
make -C /home/daniel/st/
make -C /home/daniel/st/ clean install

echo "###########################################"
echo "coping config files"
echo "###########################################"

su daniel -c "mkdir  /home/daniel/.local/share/Trash"
su daniel -c "mkdir /home/daniel/backups/"
su daniel -c "cp -v ~/* /home/daniel/backups/"
su daniel -c "cp -v ~/.* /home/daniel/backups/"

su daniel -c "stow shell config"
su daniel -c "chmod 744 -R /home/daniel/scripts"
su daniel -c "sed -i '/daniel torres/,$d' /home/daniel/.bashrc"
su daniel -c "cat /home/daniel/.bashrc_tail >> /home/daniel/.bashrc"

su daniel -c "chmod 774 /home/daniel/.config/bspwm/bspwmrc"
su daniel -c "chmod 774 /home/daniel/.config/sxhkd/sxhkdrc"
su daniel -c "chmod 774 /home/daniel/.config/polybar/launch.sh"

echo "######################################################"
echo "installing window manager"
echo "XF86_keyboard_symbols complete list:" 
echo "wiki.linuxquestions.org/wiki/XF86_keyboard_symbols"
echo "######################################################"

echo "***** bspwm *****"
pacman -S --needed --noconfirm bspwm sxhkd polybar

echo "***** emacs *****"
su daniel -c "git clone https://github.com/danieltorrescode/emacs.git /home/daniel/.emacs.d"

echo "***** vim *****"
su daniel -c "git clone https://github.com/VundleVim/Vundle.vim.git /home/daniel/.vim/bundle/Vundle.vim"

echo "***** paru *****"
pacman -S --needed --noconfirm go
su daniel -c "git clone https://aur.archlinux.org/paru.git /home/daniel/paru"
chown -R  daniel:daniel /home/daniel/paru
cd /home/daniel/paru
echo "run: makepkg -si"
echo "then run: paru --version"
su daniel

rm -rf /dotfiles

echo "###########################################"
echo "end"
date +'%d/%m/%Y %I:%M:%S'
echo "###########################################"
exit
