#!/bin/bash

# dwm status bar
dte(){
    dte="$(date '+%d-%m-%Y %I:%M:%S')"
    echo "$dte"
}

keysindicator(){
    CAPS_STATUS=`xset q | grep -i caps | cut -c 22-24`
    STATUS="Caps:$CAPS_STATUS"

    NUM_STATUS=`xset q | grep -i caps | cut -c 46-48`
    STATUS="$STATUS | Num:$NUM_STATUS"
    echo "$STATUS"
}

IF=$(ip route | awk '/^default/ { print $5 ; exit }')

IF_STATE=$(cat /sys/class/net/$IF/operstate)

IPADDR=$(ip addr show $IF | perl -n -e "/inet ([^\/]+).* scope global/ && print \$1 and exit")

BATTERY=$(acpi -i | grep 1 | cut -d, -f-2 | cut -d: -f2-)

# echo "$(keysindicator) | $IF $IF_STATE $IPADDR | $BATTERY | $(dte)"
echo "$(keysindicator) | $IF $IF_STATE | $(dte)"
