#!/bin/bash
colors=$1
if [ ${colors:=0} -gt 0 ]
then
    for((i=16; i<256; i++)); do
        printf "\e[48;5;${i}m%03d" $i;
        printf '\e[0m';
        [ ! $((($i - 15) % 6)) -eq 0 ] && printf ' ' || printf '\n'
    done
    # check Xterm code list 
    # convert hexadeciaml to  ANSI color code
    # search for web cheatsheet to check convertion
else
    echo $0
fi


# start=`grep -n "daniel torres"  /home/daniel/.bashrc | awk -F ":" '{ print $1 }'`
# bashrc=`tail -n 1 /home/daniel/.bashrc`
# newlines=`tail -n 1 /home/daniel/.bashrc`
# bashrc=`awk '/daniel torres/ { print $1}' /home/daniel/.bashrc`

# if [ $bashrc ]
# then
#     echo ".bashrc already modified"
# else
#     su daniel -c "cat dotfiles/.bashrc >> /home/daniel/.bashrc"
# fi