#!/bin/bash

# https://man.archlinux.org/man/libinput.4
device=$1
touchpad="Touchpad"
$device=${device:=$touchpad}
xinput list
xinput list | grep $device
# $device = xinput list | awk 'BEGIN { FS="=" } /Touchpad/ { print $2 ; exit }' | awk '{print $1 ; exit}'
device=`xinput list | awk -v device="$device" 'BEGIN { FS="=" } $0~device { print $2 ; exit }' | awk '{print $1 ; exit}'`
echo "##########################################"
echo "Tapping Enabled"
echo "##########################################"
xinput --set-prop $device "libinput Tapping Enabled"  1
echo "Tapping Drag Enabled"
echo "##########################################"
xinput --set-prop $device "libinput Tapping Drag Enabled" 1
echo "Tapping Drag Lock Enabled"
echo "##########################################"
xinput --set-prop $device "libinput Tapping Drag Lock Enabled" 0
echo "Tapping Button Mapping Enabled"
echo "##########################################"
xinput --set-prop $device "libinput Tapping Button Mapping Enabled" 1, 0
echo "Natural Scrolling Enabled"
echo "##########################################"
xinput --set-prop $device "libinput Natural Scrolling Enabled" 1
echo "Disable While Typing Enabled"
echo "##########################################"
xinput --set-prop $device "libinput Disable While Typing Enabled" 1
echo "Scroll Methods Available"
echo "##########################################"
xinput --set-prop $device "libinput Scroll Methods Available" 1, 1, 0
echo "Scroll Method Enabled"
echo "##########################################"
xinput --set-prop $device "libinput Scroll Method Enabled" 1, 0, 0
echo "Click Methods Available"
echo "##########################################"
xinput --set-prop $device "libinput Click Methods Available" 1, 1
echo "Click Method Enabled"
echo "##########################################"
xinput --set-prop $device "libinput Click Method Enabled" 1, 0
echo "Middle Emulation Enabled"
echo "##########################################"
xinput --set-prop $device "libinput Middle Emulation Enabled" 0
echo "Accel Speed"
echo "##########################################"
xinput --set-prop $device "libinput Accel Speed" 1.000000
echo "Accel Profiles Available"
echo "##########################################"
xinput --set-prop $device "libinput Accel Profiles Available" 1, 1
echo "Accel Profile Enabled"
echo "##########################################"
xinput --set-prop $device "libinput Accel Profile Enabled" 1, 0
echo "Left Handed Enabled"
echo "##########################################"
xinput --set-prop $device "libinput Left Handed Enabled" 0
echo "Send Events Modes Available"
echo "##########################################"
xinput --set-prop $device "libinput Send Events Modes Available" 1, 1
echo "Send Events Mode Enabled"
echo "##########################################"
xinput --set-prop $device "libinput Send Events Mode Enabled" 0, 0
echo "Horizontal Scroll Enabled"
echo "##########################################"
xinput --set-prop $device "libinput Horizontal Scroll Enabled" 1
echo "Scrolling Pixel Distance"
echo "##########################################"
xinput --set-prop $device "libinput Scrolling Pixel Distance" 15
echo "High Resolution Wheel Scroll Enabled"
echo "##########################################"
xinput --set-prop $device "libinput High Resolution Wheel Scroll Enabled" 1