#!/bin/bash

apt install vim git tmux gparted keepassxc htop -y
apt install  ufw gufw liferea powerline gnome-tweaks -y
apt install  qemu qemu-kvm virt-manager bridge-utils docker.io docker-compose  -y
apt install  kitty fzf neofetch bat fonts-hack pip virtualenv -y
apt install  sway swaybg swaylock waybar wdisplays wofi swayimg swayidle -y
apt install  sway-backgrounds python3-i3ipc grimshot mako-notifier -y
apt install  zsh zsh-theme-powerlevel9k zsh-syntax-highlighting zsh-autosuggestions -y
apt install  playerctl brightnessctl ffmpeg pavucontrol -y
apt install  bspwm sxhkd polybar rofi feh picom xserver-xorg-input-synaptics -y

chmod 666  /sys/class/backlight/amdgpu_bl0/brightness
snap install lsd
snap install --edge starship 

python3 -m pip install --upgrade pip

git clone https://github.com/danieltorrescode/dotfiles.git /home/daniel/dotfiles
cp /home/daniel/dotfiles/config/.vimrc ~

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
cp /home/daniel/dotfiles/config/.p10k.zsh ~

# cp /home/daniel/dotfiles/config/waybar ~/.config
# cp /home/daniel/dotfiles/config/sway ~/.config
# cp /home/daniel/dotfiles/config/swaylock ~/.config
# cp /home/daniel/dotfiles/config/swayidle ~/.config
            
cp /home/daniel/dotfiles/config/starship.toml ~
cp -r /home/daniel/dotfiles/config/.fonts ~/.local/share/fonts
fc-cache -f -v

# apt install dxvk winetricks
# snap install steam 
# snap install --edge heroic

usermod -aG docker daniel


chmod +x ~/.config/swaylock/lock.sh
chmod +x -R ~/scripts

# .bashrc
: <<'COMMENT'
    # "from here all is added and edited by daniel torres"
    # uncomment the line above to set to yes force_color_prompt=yes
    # default .bashrc config files at /etc/skel/

    alias SO="systemctl poweroff"
    alias SR="systemctl reboot"
    alias SS="systemctl suspend"
    alias SH="systemctl hibernate"
    alias SSH="systemctl suspend-then-hibernate"

    alias firefox2="${HOME}/firefox/firefox -P firefox2 2>/dev/null &"

    alias ll='lsd -lh --group-dirs=first'
    alias la='lsd -a --group-dirs=first'
    alias l='lsd --group-dirs=first'
    alias lla='lsd -lha --group-dirs=first'
    alias ls='lsd --group-dirs=first'
    #alias cat='bat'

    set -o vi
    bind 'set show-all-if-ambiguous on'
    bind 'TAB:menu-complete'
    uname -a
    neofetch

    #[ -f ~/.fzf.bash ] && source ~/.fzf.bash
    [ -f /usr/bin/fzf ]
    #source /usr/share/fzf/completion.bash
    source /usr/share/doc/fzf/examples/key-bindings.bash
    #export FZF_DEFAULT_OPTS="--extended"
    #export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

    export STARSHIP_CONFIG=~/starship.toml
    # Starship Prompt
    eval "$(starship init bash)"
COMMENT


# .zshrc
: <<'COMMENT'
    # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
    # Initialization code that may require console input (password prompts, [y/n]
    # confirmations, etc.) must go above this block; everything else may go below.
    if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
    fi

    uname -a
    neofetch

    HISTFILE=~/.zsh_history
    HISTSIZE=1000
    SAVEHIST=1000
    setopt notify
    unsetopt beep
    bindkey -v
    bindkey '^R' history-incremental-search-backward
    # End of lines configured by zsh-newuser-install
    # The following lines were added by compinstall
    zstyle :compinstall filename '/home/daniel/.zshrc'

    autoload -Uz promptinit
    promptinit
    autoload -Uz compinit
    compinit
    # End of lines added by compinstall

    # Manual aliases
    alias ll='lsd -lh --group-dirs=first'
    alias la='lsd -a --group-dirs=first'
    alias l='lsd --group-dirs=first'
    alias lla='lsd -lha --group-dirs=first'
    alias ls='lsd --group-dirs=first'
    alias SO="systemctl poweroff"
    alias SR="systemctl reboot"
    alias SS="systemctl suspend"
    alias SH="systemctl hibernate"
    alias SSH="systemctl suspend-then-hibernate"

    source ~/powerlevel10k/powerlevel10k.zsh-theme
    source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh

    #[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
    #[ -f /usr/bin/fzf ]
    source /usr/share/doc/fzf/examples/completion.zsh
    source /usr/share/doc/fzf/examples/key-bindings.zsh
    export FZF_DEFAULT_OPTS="--extended"
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"


    # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
    [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
COMMENT
