#! /bin/sh

# Load Xresource file
xrdb -remove *
xrdb ~/.Xresources

killall -q sxhkd
sxhkd &
# setting wallpaper
feh --bg-scale ~/Documents/Wallpapers/red_blue.jpg &

# starting picom
picom --config ~/.config/picom/picom.conf &

# starting polybar
~/.config/polybar/launch.sh &

# notifications
pkill dunst
dunst &

#### MONITORS ####
bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9
# bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9
# bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    1
bspc config top_padding                   27
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
#bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
#bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
#bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color           "#4c566a"
bspc config active_border_color         "#1e1e1e"
bspc config focused_border_color        "#d1cbbe"
bspc config presel_feedback_color         "#5e81ac"
#bspc config urgent_border_color          "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

bspc rule -a Emacs state=tiled follow=on
bspc rule -a Zathura state=tiled follow=on
bspc rule -a Surf state=tiled follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'

xsetroot -cursor_name left_ptr &
