#!/bin/bash
echo "###########################################" 
echo "updating repositories and installing essentials" 
echo "###########################################" 
apt-get update
apt-get install -y aptitude
aptitude install -y build-essential screen curl htop wget xorg 
aptitude install -y xdo xtitle clang git cmake
aptitude install -y vim vim-syntastic vim-snippets vim-youcompleteme
aptitude install -y emacs emacs-goodies-el
aptitude install -y compton feh arandr playerctl pavucontrol
aptitude install -y suckless-tools dmenu surf tabbed
aptitude install -y zathura mpv imagemagick
aptitude install -y python-pip python3-pip virtualenv
aptitude install -y pkg-config libfontconfig-dev libdbus-glib-1-2 libfreetype6-dev
aptitude install -y libx11-dev libxft-dev libxinerama1 libxinerama-dev
aptitude install -y simple-scan fonts-hack-ttf fonts-font-awesome fonts-liberation
aptitude install -y sudo iw wireless-tools wpasupplicant wicd-curses
aptitude install -y sudo newsboat mutt rtorrent transmission-cli
# aptitude install -y ufw gufw firejail apparmor lxc

echo "###########################################" 
echo "installing containers and virtual machine tools" 
echo "###########################################" 

aptitude install -y docker.io docker-compose  
# aptitude install -y qemu qemu-kvm

echo "###########################################" 
echo "creating virtualenv for python" 
echo "###########################################" 

virtualenv -p python3 ~/.venv/python
pip install --upgrade pip
virtualenv -p python3 ~/.venv/youtube-dl
pip install --upgrade pip
pip install youtube-dl

echo "###########################################" 
echo "cloning and building packages" 
echo "###########################################" 

folder="/home/daniel"
WM="bspwm"

su daniel -c "git clone https://github.com/danieltorrescode/st.git $folder/st"
rm $folder/st/config.h
make -C $folder/st/
make -C $folder/st/ clean install

# to add color to st use http://terminal.sexy/
# generate palette with pywall or colorz
# and edit st/config.def.h and rebuild 
# patching ex:
# patch < $patch
# su daniel -c "patch -d st/ < patches/$patch"

case $WM in
    "dwm")
        su daniel -c "git clone https://github.com/danieltorrescode/dwm.git $folder/dwm"
        rm $folder/$package/config.h
        make -C $folder/$package/
        make -C $folder/$package/ clean install
        ;;
    "bspwm")
        aptitude install -y bspwm sxhkd
        su daniel -c "git clone https://github.com/polybar/polybar $folder/polybar"

        aptitude install -y cmake cmake-data pkg-config 
        aptitude install -y python3-sphinx libcairo2-dev libxcb1-dev libxcb-util0-dev 
        aptitude install -y libxcb-randr0-dev libxcb-composite0-dev python3-xcbgen 
        aptitude install -y xcb-proto libxcb-image0-dev libxcb-ewmh-dev libxcb-icccm4-dev
        
        aptitude install -y libxcb-xkb-dev libxcb-xrm-dev libxcb-cursor-dev 
        aptitude install -y libasound2-dev libpulse-dev libmpdclient-dev 
        aptitude install -y libcurl4-openssl-dev libnl-genl-3-dev

        su daniel -c "mkdir $folder/polybar/build"
        su daniel -c "cmake .. --build $folder/polybar/build/"
        su daniel -c "make -j$(nproc) -C $folder/polybar/build/"
        make install -C $folder/polybar/build/
        ;;
    "i3")
        echo $WM
        aptitude install -y i3-wm i3blocks i3lock ranger
        ;;
    *)
        echo $WM
        ;;
esac
